---
apiVersion: v1
kind: Namespace
metadata:
  name: skupper-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skupper-controller
  namespace: skupper-controller
  labels:
    application: skupper-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    application: skupper-controller
  name: skupper-controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - pods/exec
  - services
  - secrets
  - serviceaccounts
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
- apiGroups:
    - apps.openshift.io
  resources:
    - deploymentconfigs
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    application: skupper-controller
  name: skupper-controller
subjects:
- kind: ServiceAccount
  name: skupper-controller
  namespace: skupper-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: skupper-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-controller
  namespace: skupper-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      application: skupper-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: skupper
        application: skupper-controller
    spec:
      serviceAccountName: skupper-controller
      containers:
      - name: site-controller
        image: quay.io/gordons/controller
        env:
        - name: ENABLE_VAULT_INTEGRATION
          value: "1"
        - name: VAULT_ADDRESS
          value: "http://vault-vault.skupper-0-153f1de160110098c1928a6c05e19444-0000.us-east.containers.appdomain.cloud"
        - name: VAULT_AUTH_METHOD
          value: "approle"
        - name: VAULT_ROLE_ID
          value: "d241167a-6dfd-b73f-17cb-4cce2eb7facb"
        - name: VAULT_SECRET_ID
          value: "$VAULT_SECRET_ID"
        - name: ZONE
          value: public
        - name: REACHABLE_FROM
          value: private,public
---
